name: Run Journey Tests

permissions:
  id-token: write
  checks: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: run-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: DEFRA/cdp-build-action/docker-login@main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}-
      - name: Setup the tests
        run: npm i
      - name: Start docker compose
        run: docker compose up --wait-timeout 300 -d --quiet-pull
      - name: Run the tests
        run: |
          npm run test:github
          npm run report
      - name: debug
        if: failure()
        run: |
          docker compose logs > logs.txt
          docker ps
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
