name: Run Journey Tests

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: run-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup the tests
        run: npm ci --omit=dev
      - name: Start docker compose
        run: docker compose up --wait-timeout 300 -d --quiet-pull
      - name: Run the tests
        run: |
          npm run test:github
          npm run report
      - name: debug
        if: failure()
        run: |
          docker compose logs > logs.txt
          docker ps
      - name: Create test summary
        uses: test-summary/action@v1
        with:
          paths: results/**/*.xml
        if: always()
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results
          path: allure-report/index.html
